---
title: "Writing Functions"
output: github_document
---
this is the repository for iteration part 1 of P8105

```{r setup}
library(tidyverse)
library(rvest)

set.seed(1)

```

## writing my first function
as an example here's a z-score computation
```{r}
x_vec = rnorm(25, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

Now i'll write a function to do this
```{r, error=FALSE}
z_scores = function(x) {

if(is.numeric(x)){
  stop('x needs to be numeric')
}
  if(length(x)<5){
    stop("you need at least five numbers to compute the z score")
  }
  
  z = (x - mean(x)) / sd(x)
  return(z)
  
}

```
Does this always work? Missing value bc you cant get the std of 1 number
```{r, error=TRUE}
z_scores(3)
z_scores("my name is jeff")
```

## A new function
```{r}
mean_and_sd = function(x){
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  out_df=
  tibble(
    mean = mean_x, 
    sd = sd_x
  )
  return(out_df)
}
mean_and_sd(x_vec)
```

## Check stuff using a simulation
```{r}
sim_df =
  tibble(
    x=rnorm(30,10,5)
  )

sim_df |>
  summarize(
    mean=mean(x),
    sd=sd(x)
  )
```

Simulation function to check sample mean and sd

```{r}
sim_mean_sd = function(samp_size, true_mean, true_sd) {
  sim_df =
  tibble(
    x=rnorm(samp_size, true_mean, true_sd)
  )

out_df=
sim_df|>
  summarize(
    mean=mean(x),
    sd=sd(x)
  )
return(out_df)
}
sim_mean_sd(samp_size = 30, true_mean = 4, true_sd= 12)
sim_mean_sd(30, 16, 2)

```

## Revist lotr dataset
```{r}
fellowship_df = readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship")

two_towers_df = readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king_df = readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")
```

```{r}
lotr_tidy = bind_rows(fellowship_df, two_towers_df, return_king_df) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words") |> 
  mutate(race = str_to_lower(race)) |> 
  select(movie, everything()) 
```

## NSDUH
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

nsduh_html = read_html(nsduh_url)
data_marj = 
  nsduh_html |> 
  html_table() |> 
  nth(1) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```

